//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyExpensesCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cFamilyMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cFamilyMember()
        {
            this.cMonthlyIncomes = new HashSet<cMonthlyIncome>();
            this.vExpenses = new HashSet<vExpense>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> FamilyRoleId { get; set; }
        public Nullable<int> FamilyId { get; set; }
    
        public virtual cFamilyRole cFamilyRole { get; set; }
        public virtual сFamily сFamily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cMonthlyIncome> cMonthlyIncomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vExpense> vExpenses { get; set; }
    }
}
