//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyExpensesCourseWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FamilyExpensesEntities : DbContext
    {
        public FamilyExpensesEntities()
            : base("name=FamilyExpensesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cExpensePurpose> cExpensePurposes { get; set; }
        public virtual DbSet<cFamilyMember> cFamilyMembers { get; set; }
        public virtual DbSet<cFamilyRole> cFamilyRoles { get; set; }
        public virtual DbSet<cIncomeCategory> cIncomeCategories { get; set; }
        public virtual DbSet<cMonthlyIncome> cMonthlyIncomes { get; set; }
        public virtual DbSet<vExpense> vExpenses { get; set; }
        public virtual DbSet<сFamily> сFamily { get; set; }
    }
}
