//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyExpensesCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class vExpense
    {
        public int Id { get; set; }

        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> ExpenseSum { get; set; }
        public Nullable<int> ExpensePurposeId { get; set; }
        public Nullable<int> FamilyMemberId { get; set; }
    
        public virtual cExpensePurpose cExpensePurpose { get; set; }
        public virtual cFamilyMember cFamilyMember { get; set; }
    }
}
